### ISSUE TITLE
Feature Request: Better versioning?

### ISSUE THREAD

**Issue by playpauseandstop** [sloria/pre-commit-docker#1]
Hi Steven,

First of all, thanks for your effort, I ran into completely same issue, while setting up running pre-commit hooks on GitLab CI and thinking about: _There should be a docker image for that..._ 😄 

But as a paranoid I want to discuss better docker images versioning with you. As of now it is able to pull from,

- `sloria/pre-commit` (seems like Python 3.7.2 + pre-commit 1.14.2)
- and `sloria/pre-commit:py36` (Python 3.6.8 + pre-commit 1.14.2, am I right?)

But what if new `pre-commit` version released, and I'd like to use it, or what if you'll upgrade master and new unwanted `pre-commit` version will ship into container?

Maybe it is better to allow use images as,

- `sloria/pre-commit:py<PYTHON_VERSION>-<PRE_COMMIT_VERSION>`,

like,

- `sloria/pre-commit:py3.7.2-1.14.2`

I'm not sure how technically achieve it, but I'm aware of wide range of tags for official Python images (`python:3`, `python:3.7`, `python:3.7.2`, etc), so this is for sure possible.

Thanks, Igor

**Comment by sloria** [comment]
Yeah, I thought about doing something like that but didn't bother implementing it because I don't need it. The pre-commit CLI has been pretty stable since I started using it, and I didn't want to over-complicate the build process for this repo.

If you come up with a low-maintenance approach to achieving this, though, I'm open to ideas.

**Comment by playpauseandstop** [comment]
Thanks for your response. 

Your arguments are vaild and clear, let have `sloria/pre-commit` image as is, so feel free close this as `wontfix` now.

**Comment by sloria** [comment]
Thanks for understanding. We can always revisit this if the need arises.
